runs:
  using: composite
  steps:
    # we don't really care what python version we have, but maybe in the future
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies

    - run: pip3 install -r installer/requirements.txt 2>&1
      shell: bash

    # check syntax and run tests
    - run: python3 -m compileall -q . 2>&1
      shell: bash
    - run: python3 installer/tests.py 2>&1
      shell: bash

    - name: Build
      run: python3 installer/build.py
      shell: bash
    - run: du -ha installer/dist
      shell: bash

    - run: cat installer/build/installer/warn-installer.txt
      shell: bash

    # small test, use timeouts because on windows the GUI can catch errors and a dialog box will freeze the program
    - run: timeout 30 ./installer/dist/DXRandoInstaller --version --verbose 2>&1
      shell: bash
    - run: timeout 30 ./installer/dist/BingoViewer --version 2>&1
      shell: bash

    # make sure we got everything
    - run: find installer/3rdParty/
      shell: bash
    - run: find installer/dist/
      shell: bash
    - run: ls -lah installer/dist/
      shell: bash
