runs:
  using: composite
  steps:
    # we don't really care what python version we have, but maybe in the future
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies

    - run: pip3 install -r installer/requirements.txt 2>&1
      shell: bash

    # download launchers
    - run: mkdir installer/3rdParty
      shell: bash
    # https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/tree/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/Alternative%20EXEs
    - run: >-
        curl -Lo installer/3rdParty/KentieDeusExe.exe
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/Alternative%20EXEs/Kentie's%20DeusExe.exe"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/Launch.exe
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/Alternative%20EXEs/Launch.exe"
      shell: bash

    # download D3D9
    - run: >-
        curl -Lo installer/3rdParty/D3D9Drv.dll
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/D3D9Drv.dll"
      shell: bash
    #- run: >-
    #    curl -Lo installer/3rdParty/D3D9Drv.hut
    #    "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/D3D9Drv.hut"
    #  shell: bash
    #- run: >-
    #    curl -Lo installer/3rdParty/D3D9Drv.int
    #    "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/D3D9Drv.int"
    #  shell: bash

    # download and extract OpenGL 2.0 https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/tree/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/CommunityUpdateFileArchiveDXPC/OpenGL
    - run: >-
        curl -Lo dxglr21.zip
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/CommunityUpdateFileArchiveDXPC/OpenGL/dxglr21.zip"
      shell: bash
    - run: unzip dxglr21.zip
      shell: bash
    - run: cp OpenGLDrv.dll installer/3rdParty/OpenGLDrv.dll
      shell: bash

    # download D3D10 stuff
    - run: mkdir installer/3rdParty/d3d10drv
      shell: bash

    - run: >-
        curl -Lo installer/3rdParty/D3D10Drv.int
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/D3D10Drv.int"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv.dll
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv.dll"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/common.fxh
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/common.fxh"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/complexsurface.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/complexsurface.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/finalpass.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/finalpass.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/firstpass.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/firstpass.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/fogsurface.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/fogsurface.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/gouraudpolygon.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/gouraudpolygon.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/hdr.original.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/hdr%20(original).fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/hdr.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/hdr.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/polyflags.fxh
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/polyflags.fxh"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/postprocessing.fxh
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/postprocessing.fxh"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/states.fxh
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/states.fxh"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/tile.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/tile.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/unreal_pom.fx
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/unreal_pom.fx"
      shell: bash
    - run: >-
        curl -Lo installer/3rdParty/d3d10drv/unrealpool.fxh
        "https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/raw/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/DXCU%20Installer%20Source/Mods/Community%20Update/System/d3d10drv/unrealpool.fxh"
      shell: bash

    # LDDP minimal install
    - run: >-
        curl -Lo installer/3rdParty/FemJC.u
        "https://github.com/LayDDentonProject/Lay-D-Denton-Project/releases/download/v1.1/FemJC.u"
      shell: bash

    # download DXVK 32bit, the extracted folder has the version number in it like dxvk-2.3
    - run: >-
        curl -Lo dxvk.tar.gz
        "https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz"
      shell: bash
    - run: tar -xf dxvk.tar.gz
      shell: bash
    - run: mkdir installer/3rdParty/dxvk/
      shell: bash
    - run: cp dxvk-*/x32/* installer/3rdParty/dxvk/
      shell: bash

    # check syntax and run tests
    - run: python3 -m compileall -q . 2>&1
      shell: bash
    - run: python3 installer/tests.py 2>&1
      shell: bash

    - name: Build
      run: pyinstaller installer/installer.spec
      shell: bash
    - run: du -ha dist
      shell: bash

    - run: cat build/installer/warn-installer.txt
      shell: bash

    # small test, use timeouts because on windows the GUI can catch errors and a dialog box will freeze the program
    - run: timeout 30 ./dist/DXRandoInstaller --version --verbose 2>&1
      shell: bash
    - run: timeout 30 ./dist/BingoViewer --version 2>&1
      shell: bash

    # zip it up
    # - if: runner.os == 'Windows'
    #   run: Compress-Archive -Path ./* -Destination DXRando.zip
    #   working-directory: ./dist/DXRando/
    #   shell: pwsh
    # - if: runner.os == 'Windows'
    #   run: Compress-Archive -Path ./* -Destination BingoViewer.zip
    #   working-directory: ./dist/BingoViewer/
    #   shell: pwsh
    # - if: runner.os != 'Windows'
    #   run: zip -r9 DXRando.zip .
    #   working-directory: ./dist/DXRando
    #   shell: bash
    # - if: runner.os != 'Windows'
    #   run: zip -r9 BingoViewer.zip .
    #   working-directory: ./dist/BingoViewer
    #   shell: bash

    # make sure we got everything
    - run: find installer/3rdParty/
      shell: bash
    - run: find dist/
      shell: bash
    - run: ls -lah dist/
      shell: bash
